# Generated by Django 5.2.12 on 2026-03-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='エリア名')),
                ('rows', models.PositiveIntegerField(default=1, verbose_name='行数(縦)')),
                ('cols', models.PositiveIntegerField(default=1, verbose_name='列数(横)')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科の名前')),
                ('description', models.TextField(blank=True, verbose_name='特徴・注意点')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(verbose_name='行番号')),
                ('col_index', models.IntegerField(verbose_name='列番号')),
                ('width_cm', models.FloatField(default=30.0)),
                ('height_cm', models.FloatField(default=30.0)),
                ('description', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='crops.gardenarea')),
            ],
            options={
                'ordering': ['row_index', 'col_index'],
                'unique_together': {('area', 'row_index', 'col_index')},
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='野菜名')),
                ('variety', models.CharField(blank=True, max_length=50, verbose_name='品種')),
                ('planted_at', models.DateField(verbose_name='植え付け日')),
                ('plot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_crop', to='crops.plot')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='crops.vegetablefamily', verbose_name='科')),
            ],
        ),
    ]
