# Generated by Django 5.2.12 on 2026-03-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='width_cm',
        ),
        migrations.AddField(
            model_name='crop',
            name='main_plot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_here', to='crops.plot'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='crops.vegetablefamily'),
        ),
        migrations.AlterField(
            model_name='gardenarea',
            name='cols',
            field=models.PositiveIntegerField(default=10, verbose_name='横(10cm単位)'),
        ),
        migrations.AlterField(
            model_name='gardenarea',
            name='rows',
            field=models.PositiveIntegerField(default=10, verbose_name='縦(10cm単位)'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_plots', to='crops.gardenarea'),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='畝名')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='crops.gardenarea')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='crops.bed'),
        ),
    ]
