# Generated by Django 5.2.12 on 2026-03-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_remove_crop_plot_remove_plot_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.CreateModel(
            name='VegetableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='野菜名')),
                ('spacing_cm', models.PositiveIntegerField(default=50, help_text='株間の目安（例：トマトなら50cm）', verbose_name='栽培間隔(cm)')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.vegetablefamily')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='vegetable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.vegetabletype', verbose_name='野菜の種類'),
        ),
    ]
