# Generated by Django 5.2.12 on 2026-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_remove_crop_name_vegetabletype_crop_vegetable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetabletype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='crop_icons/', verbose_name='アイコン画像'),
        ),
    ]
