# Generated by Django 5.2.12 on 2026-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_vegetabletype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetabletype',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG形式だと拡大しても綺麗に表示されます', null=True, upload_to='crop_icons/', verbose_name='アイコン画像'),
        ),
    ]
