# Generated by Django 5.2.12 on 2026-03-27 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_alter_vegetabletype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetabletype',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetable_types', to='crops.vegetablefamily'),
        ),
        migrations.AlterField(
            model_name='vegetabletype',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG形式だと拡大しても綺麗に表示されます', null=True, upload_to='アイコン(SVG推奨)', verbose_name='アイコン画像'),
        ),
    ]
