# Generated by Django 5.2.12 on 2026-03-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_alter_vegetabletype_family_alter_vegetabletype_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='family',
        ),
    ]
