# Generated by Django 5.2.12 on 2026-03-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_remove_crop_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='expected_harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='収穫予定日'),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvested_at',
            field=models.DateField(blank=True, null=True, verbose_name='実際の収穫日'),
        ),
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(choices=[('planned', '計画中'), ('growing', '栽培中'), ('harvested', '収穫済')], default='growing', max_length=20),
        ),
    ]
