# Generated by Django 5.2.12 on 2026-03-29 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_crop_expected_harvest_date_crop_harvested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='deleted_at',
            field=models.DateField(blank=True, null=True, verbose_name='撤去日'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='畝立て日'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='vegetable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_here', to='crops.vegetabletype', verbose_name='野菜の種類'),
        ),
    ]
