# Generated by Django 5.2.12 on 2026-03-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_bed_deleted_at_alter_bed_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='vegetable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.vegetabletype', verbose_name='野菜の種類'),
        ),
    ]
