# Generated by Django 5.2.12 on 2026-03-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_alter_crop_vegetable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilStatusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('plowed', '耕うん済'), ('limed', '石灰投入済'), ('manured', '堆肥投入済'), ('mulched', 'マルチ展開中'), ('covered', '防虫ネット/不織布')], max_length=20, verbose_name='状態/作業内容')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了予定日')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.gardenarea')),
                ('plots', models.ManyToManyField(related_name='status_areas', to='crops.plot')),
            ],
        ),
    ]
