# Generated by Django 5.2.12 on 2026-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0011_soilstatusarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='bed',
        ),
        migrations.AddField(
            model_name='bed',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='beds', to='crops.plot'),
        ),
    ]
