# Generated by Django 5.2.12 on 2026-04-02 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_remove_plot_bed_bed_plots'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('watering', '水やり'), ('fertilizing', '追肥'), ('weeding', '除草'), ('pruning', '芽かき・剪定'), ('pest_control', '防虫・消毒'), ('harvesting', '収穫')], max_length=20, verbose_name='作業種類')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('worked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実施日時')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.gardenarea')),
                ('plots', models.ManyToManyField(related_name='maintenance_logs', to='crops.plot')),
            ],
            options={
                'verbose_name': 'お手入れ記録',
            },
        ),
    ]
