# Generated by Django 5.2.12 on 2026-04-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0014_maintenancelog_image_maintenancelog_plot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={},
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='area',
        ),
    ]
