# Generated by Django 5.2.12 on 2026-04-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0015_alter_maintenancelog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancelog',
            name='plot',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='crops.gardenarea'),
            preserve_default=False,
        ),
    ]
