# Generated by Django 5.2.12 on 2026-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0016_remove_maintenancelog_plot_maintenancelog_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='task_type',
            field=models.CharField(choices=[('watering', '水やり'), ('fertilizing', '追肥'), ('weeding', '除草'), ('pruning', '芽かき・剪定'), ('pest_control', '防虫・消毒'), ('harvesting', '収穫'), ('other', 'その他')], max_length=20, verbose_name='作業種類'),
        ),
    ]
