# Generated by Django 5.2.12 on 2026-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0017_alter_maintenancelog_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='task_type',
            field=models.CharField(choices=[('watering', '水やり'), ('fertilizing', '追肥'), ('weeding', '除草'), ('pruning', '芽かき・間引き'), ('pest_control', '防虫・消毒'), ('harvesting', '収穫'), ('other', 'その他')], max_length=20, verbose_name='作業種類'),
        ),
    ]
