# Generated by Django 5.2.12 on 2026-04-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crops', '0019_gardenarea_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenarea',
            name='user',
        ),
        migrations.AddField(
            model_name='gardenarea',
            name='owner_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardens', to='auth.group'),
        ),
    ]
