# Generated by Django 5.2.12 on 2026-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0020_remove_gardenarea_user_gardenarea_owner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetabletype',
            name='planting_type',
            field=models.CharField(choices=[('individual', '個体植え'), ('dense', '密集・筋蒔き')], default='individual', max_length=20),
        ),
    ]
