# Generated by Django 5.2.12 on 2026-04-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0021_vegetabletype_planting_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetabletype',
            old_name='planting_type',
            new_name='planting_method',
        ),
    ]
