# Generated by Django 5.2.12 on 2026-04-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0022_rename_planting_type_vegetabletype_planting_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='crops', to='crops.plot'),
        ),
        migrations.AlterField(
            model_name='vegetabletype',
            name='planting_method',
            field=models.CharField(choices=[('individual', '個体植え'), ('dense', '密集・筋蒔き')], default='individual', max_length=20, verbose_name='栽培方法'),
        ),
    ]
