# Generated by Django 5.2.12 on 2026-04-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0023_crop_plots_alter_vegetabletype_planting_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_maintenance_logs', to='crops.bed'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='crops.crop'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='plots',
            field=models.ManyToManyField(related_name='plot_maintenance_logs', to='crops.plot'),
        ),
    ]
