# Generated by Django 5.2.12 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetabletype',
            name='color',
            field=models.CharField(default='#4CAF50', max_length=7, verbose_name='表示色(hex)'),
        ),
    ]
