# Generated by Django 5.2.12 on 2026-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_vegetabletype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetabletype',
            name='icon',
            field=models.FileField(blank=True, help_text='SVG形式推奨', null=True, upload_to='vegetables/icons/', verbose_name='アイコン画像'),
        ),
    ]
