# Generated by Django 5.2.12 on 2026-03-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='作業日')),
                ('task', models.CharField(choices=[('watering', '水やり'), ('fertilizing', '追肥'), ('weeding', '除草'), ('pruning', '整枝・脇芽取り'), ('harvesting', '収穫'), ('other', 'その他')], max_length=20, verbose_name='作業内容')),
                ('note', models.TextField(blank=True, verbose_name='メモ・気づき')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='写真')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crops.crop', verbose_name='対象の野菜')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.plot', verbose_name='作業場所')),
            ],
            options={
                'verbose_name': '作業記録',
                'ordering': ['-date'],
            },
        ),
    ]
