# Generated by Django 5.2.12 on 2026-06-27 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科の名前')),
                ('description', models.TextField(blank=True, verbose_name='特徴・注意点')),
            ],
        ),
        migrations.CreateModel(
            name='GardenArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='エリア名')),
                ('rows', models.PositiveSmallIntegerField(default=180, verbose_name='縦(10cm単位)')),
                ('cols', models.PositiveSmallIntegerField(default=70, verbose_name='横(10cm単位)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden2_areas', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(blank=True, max_length=50, verbose_name='品種')),
                ('row_start', models.PositiveSmallIntegerField(verbose_name='開始行(10cm単位)')),
                ('col_start', models.PositiveSmallIntegerField(verbose_name='開始列(10cm単位)')),
                ('row_end', models.PositiveSmallIntegerField(verbose_name='終了行(10cm単位)')),
                ('col_end', models.PositiveSmallIntegerField(verbose_name='終了列(10cm単位)')),
                ('planted_at', models.DateField(verbose_name='植え付け日')),
                ('expected_harvest_date', models.DateField(blank=True, null=True, verbose_name='収穫予定日')),
                ('harvested_at', models.DateField(blank=True, null=True, verbose_name='実際の収穫日')),
                ('status', models.CharField(choices=[('planned', '計画中'), ('growing', '栽培中'), ('harvested', '収穫済')], default='growing', max_length=20, verbose_name='状態')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='garden2.gardenarea')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='畝名')),
                ('row_start', models.PositiveSmallIntegerField(verbose_name='開始行(10cm単位)')),
                ('col_start', models.PositiveSmallIntegerField(verbose_name='開始列(10cm単位)')),
                ('row_end', models.PositiveSmallIntegerField(verbose_name='終了行(10cm単位)')),
                ('col_end', models.PositiveSmallIntegerField(verbose_name='終了列(10cm単位)')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='畝立て日')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='撤去日')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='garden2.gardenarea')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('watering', '水やり'), ('fertilizing', '追肥'), ('weeding', '除草'), ('pruning', '芽かき・間引き'), ('pest_control', '防虫・消毒'), ('harvesting', '収穫'), ('other', 'その他')], max_length=20, verbose_name='作業種類')),
                ('row_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='開始行(10cm単位)')),
                ('col_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='開始列(10cm単位)')),
                ('row_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='終了行(10cm単位)')),
                ('col_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='終了列(10cm単位)')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('worked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実施日時')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logs/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='garden2.gardenarea')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='garden2.bed')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='garden2.crop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garden2_maintenance_logs', to=settings.AUTH_USER_MODEL, verbose_name='作業者')),
            ],
        ),
        migrations.CreateModel(
            name='SoilStatusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('plowed', '耕うん済'), ('limed', '石灰投入済'), ('manured', '堆肥投入済'), ('mulched', 'マルチ展開中'), ('covered', '防虫ネット/不織布')], max_length=20, verbose_name='状態/作業内容')),
                ('row_start', models.PositiveSmallIntegerField(verbose_name='開始行(10cm単位)')),
                ('col_start', models.PositiveSmallIntegerField(verbose_name='開始列(10cm単位)')),
                ('row_end', models.PositiveSmallIntegerField(verbose_name='終了行(10cm単位)')),
                ('col_end', models.PositiveSmallIntegerField(verbose_name='終了列(10cm単位)')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了予定日')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_status_areas', to='garden2.gardenarea')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='野菜名')),
                ('icon', models.FileField(blank=True, help_text='SVG形式推奨', null=True, upload_to='vegetables/icons/', verbose_name='アイコン画像')),
                ('spacing_cm', models.PositiveSmallIntegerField(default=50, verbose_name='株間(cm)')),
                ('planting_method', models.CharField(choices=[('individual', '1株ずつ'), ('row', '筋蒔き'), ('block', 'まとめ植え')], default='individual', max_length=20, verbose_name='栽培方法')),
                ('rotation_years', models.PositiveSmallIntegerField(default=3, verbose_name='連作回避年数')),
                ('rotation_buffer_cm', models.PositiveSmallIntegerField(default=50, verbose_name='影響半径(cm)')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='表示色(hex)')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetable_types', to='garden2.vegetablefamily')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='vegetable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden2.vegetabletype', verbose_name='野菜の種類'),
        ),
    ]
