# Generated by Django 5.2.12 on 2026-06-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablefamily',
            name='color',
            field=models.CharField(default='#8a8067', help_text='畑マップで使う科の代表色（例：#b3564a）', max_length=7, verbose_name='表示色(hex)'),
        ),
    ]
