# Generated by Django 5.2.12 on 2026-06-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden2', '0004_grid_5cm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='col_end',
            field=models.PositiveSmallIntegerField(verbose_name='終了列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='col_start',
            field=models.PositiveSmallIntegerField(verbose_name='開始列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='row_end',
            field=models.PositiveSmallIntegerField(verbose_name='終了行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='row_start',
            field=models.PositiveSmallIntegerField(verbose_name='開始行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='col_end',
            field=models.PositiveSmallIntegerField(verbose_name='終了列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='col_start',
            field=models.PositiveSmallIntegerField(verbose_name='開始列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='row_end',
            field=models.PositiveSmallIntegerField(verbose_name='終了行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='row_start',
            field=models.PositiveSmallIntegerField(verbose_name='開始行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='gardenarea',
            name='cols',
            field=models.PositiveSmallIntegerField(default=140, verbose_name='横(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='gardenarea',
            name='rows',
            field=models.PositiveSmallIntegerField(default=360, verbose_name='縦(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='col_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='終了列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='col_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='開始列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='row_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='終了行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='row_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='開始行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='soilstatusarea',
            name='col_end',
            field=models.PositiveSmallIntegerField(verbose_name='終了列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='soilstatusarea',
            name='col_start',
            field=models.PositiveSmallIntegerField(verbose_name='開始列(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='soilstatusarea',
            name='row_end',
            field=models.PositiveSmallIntegerField(verbose_name='終了行(5cm単位)'),
        ),
        migrations.AlterField(
            model_name='soilstatusarea',
            name='row_start',
            field=models.PositiveSmallIntegerField(verbose_name='開始行(5cm単位)'),
        ),
    ]
