# Generated by Django 5.2.12 on 2026-06-29 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden2', '0005_default_5cm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenarea',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_garden2_areas', to=settings.AUTH_USER_MODEL, verbose_name='共有メンバー'),
        ),
    ]
